### ISSUE TITLE
Editing

### ISSUE THREAD

**Issue by ZachAndrews98** [cerdamejiaj/about-me#1]
Commit: 10444e90c001f1bf58e78ba7409ccd241ec2194c
Paragraph 1:
Edit- first sentence to make sense- "was born in...".
Edit- remove "I lived a majority of my childhood there until I was 11 and moved to the United States" from the first paragraph
Edit- "and My father was there"- uncapitalize My and state specifically where there is.
Edit- can use a pronoun to refer to the Internet Cafe after referring to it once.
Edit- merge the last two sentences.
Paragraph 2:
Edit- clean up second sentence runs on especially "how videos games were created and also websites" feels forced into the sentence
Paragraph 3:
Edit- make programming language plural since you learned about 2 languages
Edit- remove "where I had the chance to spend" and replace it with "where I spent"
Edit- replace "where we formed a group" with "where I formed a group"
Edit- make "partner" past tense 
Edit- replace "eventually I decided to major" with "my major"

**Comment by jonathanwmendez** [comment]
Latest Commit: 

**Paragraph One**

- In the last sentence "It was the first time I ever played or used the Internet on a computer. It was an amazing first experience that changed me for the better." I think that you should change "me for the better." with my life or my life for the better.
